### ISSUE TITLE
not an issue just asking

### ISSUE THREAD

**Issue by Ravan1190** [dj-yacine-flutter/android_vlc_player#1]
does it supports hls , dash, ?

if not can you please make an package on that which supports hls[.m3u8 links] , Dash(track, subtitles, audio track selection, .mpd links), DRM support (clearkey, token, Widevine, FairPlay EZDRM).

Like Network Stream App ?

**Comment by djeddi-yacine** [comment]
> does it supports hls , dash, ?
> 
> if not can you please make an package on that which supports hls[.m3u8 links] , Dash(track, subtitles, audio track selection, .mpd links), DRM support (clearkey, token, Widevine, FairPlay EZDRM).
> 
> Like Network Stream App ?

Yes it support m3u8 links
